import { describe, it, expect } from "vitest";
import {
  diffTokens,
  flattenTheme,
  generateThemeSource,
  nestTokens,
  renderTokenDiff,
  rgbaToHex,
  tokensFromFigmaVariables,
  type FigmaVariablesPayload,
} from "../src/index.js";

const payload: FigmaVariablesPayload = {
  modeId: "light",
  variables: [
    { id: "V:1", name: "color/bg/accent", resolvedType: "COLOR", valuesByMode: { light: { r: 0.145, g: 0.388, b: 0.922, a: 1 } } },
    { id: "V:2", name: "color/text/on-accent", resolvedType: "COLOR", valuesByMode: { light: { r: 1, g: 1, b: 1, a: 1 } } },
    { id: "V:3", name: "radius/md", resolvedType: "FLOAT", valuesByMode: { light: 8 } },
    { id: "V:4", name: "flag/x", resolvedType: "BOOLEAN", valuesByMode: { light: true } }, // skipped
  ],
};

describe("tokensFromFigmaVariables", () => {
  it("normalizes names to dot-refs and colors to hex", () => {
    const tokens = tokensFromFigmaVariables(payload);
    expect(tokens["color.bg.accent"]).toBe("#2563eb"); // the fixture's accent, round-tripped
    expect(tokens["color.text.on-accent"]).toBe("#ffffff");
    expect(tokens["radius.md"]).toBe(8);
    expect(tokens["flag.x"]).toBeUndefined(); // booleans skipped
  });

  it("emits #rrggbbaa only when alpha < 1", () => {
    expect(rgbaToHex({ r: 0, g: 0, b: 0, a: 0.5 })).toBe("#00000080");
    expect(rgbaToHex({ r: 0, g: 0, b: 0, a: 1 })).toBe("#000000");
  });
});

describe("theme flatten/nest/generate", () => {
  const tokens = { "color.bg.accent": "#2563eb", "radius.md": 8, "type.label.size": 16 };

  it("round-trips flatten ∘ nest", () => {
    expect(flattenTheme(nestTokens(tokens))).toEqual(tokens);
  });

  it("generates deterministic token-only theme source", () => {
    const src = generateThemeSource(tokens);
    expect(src).toContain("GENERATED by @parity/token-sync");
    expect(src).toContain("accent:");
    expect(src).toContain('"#2563eb"');
    // deterministic: same input, same bytes
    expect(generateThemeSource(tokens)).toBe(src);
  });
});

describe("diffTokens", () => {
  const code = { "color.bg.accent": "#2563eb", "radius.md": 8 };

  it("reports in-sync when identical", () => {
    expect(diffTokens(code, code).inSync).toBe(true);
  });

  it("detects added / removed / changed", () => {
    const design = { "color.bg.accent": "#1d4ed8", "spacing.sm": 4 };
    const diff = diffTokens(design, code);
    expect(diff.inSync).toBe(false);
    const byRef = Object.fromEntries(diff.changes.map((c) => [c.ref, c.kind]));
    expect(byRef).toEqual({
      "color.bg.accent": "changed",
      "radius.md": "removed",
      "spacing.sm": "added",
    });
    const rendered = renderTokenDiff(diff);
    expect(rendered).toContain("~ color.bg.accent: #2563eb → #1d4ed8");
    expect(rendered).toContain("+ spacing.sm = 4");
    expect(rendered).toContain("- radius.md (was 8)");
  });
});
