import type { TokenSet, TokenValue } from "./types.js";

/**
 * The code side: a nested theme object ↔ the flat TokenSet. `flattenTheme` reads an
 * existing theme; `generateThemeSource` emits a fresh `theme.ts` whose ONLY content is
 * tokens — this is what a sync PR rewrites, never a component.
 */

export type ThemeObject = { [key: string]: TokenValue | ThemeObject };

/** { color: { bg: { accent: "#2563eb" } } } → { "color.bg.accent": "#2563eb" }. */
export function flattenTheme(theme: ThemeObject, prefix = ""): TokenSet {
  const out: TokenSet = {};
  for (const [key, value] of Object.entries(theme)) {
    const ref = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "object" && value !== null) {
      Object.assign(out, flattenTheme(value, ref));
    } else {
      out[ref] = value;
    }
  }
  return out;
}

/** Inverse of flattenTheme. */
export function nestTokens(tokens: TokenSet): ThemeObject {
  const root: ThemeObject = {};
  // Sort for deterministic output — stable diffs are the whole point.
  for (const ref of Object.keys(tokens).sort()) {
    const parts = ref.split(".");
    let node = root;
    for (const part of parts.slice(0, -1)) {
      const next = node[part];
      if (typeof next === "object" && next !== null) {
        node = next;
      } else {
        const created: ThemeObject = {};
        node[part] = created;
        node = created;
      }
    }
    node[parts[parts.length - 1]!] = tokens[ref]!;
  }
  return root;
}

/** Emit theme.ts source. Deterministic (sorted keys) so diffs are token-only and minimal. */
export function generateThemeSource(tokens: TokenSet): string {
  const nested = nestTokens(tokens);
  const body = JSON.stringify(nested, null, 2)
    // JSON quotes keys; theme.ts uses bare identifiers where legal for readability.
    .replace(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, "$1:");
  return [
    "// GENERATED by @parity/token-sync — do not edit by hand.",
    "// Source of truth: Figma Variables. A token change lands as a PR containing only this file.",
    `export const theme = ${body} as const;`,
    "",
  ].join("\n");
}
